export const physics5 = [
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Work Done",
      formula: "W = F * d * cos(θ)",
      description: "Work is done when a force causes displacement; θ is the angle between force and displacement.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Positive Work",
      formula: "θ < 90°",
      description: "Work is positive when force has a component in the direction of displacement.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Negative Work",
      formula: "θ > 90°",
      description: "Work is negative when force opposes displacement.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Zero Work",
      formula: "θ = 90°",
      description: "No work is done when force is perpendicular to displacement.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Kinetic Energy",
      formula: "KE = 1/2 * m * v^2",
      description: "Energy possessed by a body due to its motion.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Potential Energy",
      formula: "PE = m * g * h",
      description: "Energy possessed by a body due to its position or configuration.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Work-Energy Theorem",
      formula: "W = ΔKE = KE_final - KE_initial",
      description: "Net work done by forces is equal to the change in kinetic energy.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Conservation of Mechanical Energy",
      formula: "Total Energy = KE + PE = constant",
      description: "In the absence of non-conservative forces, total mechanical energy remains constant.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Power",
      formula: "P = W / t",
      description: "Rate at which work is done or energy is transferred.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Instantaneous Power",
      formula: "P = F * v * cos(θ)",
      description: "Power at any instant when force and velocity are given.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Average Power",
      formula: "P_avg = Total Work / Total Time",
      description: "Average rate of work done over a time interval.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Efficiency",
      formula: "Efficiency = (Useful Power Output / Total Power Input) * 100%",
      description: "Efficiency is the ratio of useful output to input, expressed as a percentage.",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Spring Potential Energy",
      formula: "U = 1/2 * k * x^2",
      description: "Potential energy stored in a stretched or compressed spring (Hooke’s Law).",
    },
    {
      topic: "physics",
      chapter: "Work, Energy and Power",
      name: "Work by a Spring",
      formula: "W = -1/2 * k * x^2",
      description: "Work done by a spring force when stretched/compressed by x.",
    }
  ];
  