export const physics2 = [
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Coulomb's Law",
      formula: "F⃗ = k × (q₁ × q₂) ÷ r²",
      description: "The electrostatic force (F) between two charges is directly proportional to the product of the charges and inversely proportional to the square of the distance between them.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Electrostatic Constant",
      formula: "k = 1 ÷ (4 × π × ε₀)",
      description: "k is Coulomb's constant, where ε₀ is the permittivity of free space (≈ 8.85 × 10⁻¹² C²/N·m²).",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Electric Field",
      formula: "E⃗ = F⃗ ÷ q",
      description: "Electric field is the force experienced by a unit positive charge.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Electric Field Due to a Point Charge",
      formula: "E⃗ = k × q ÷ r²",
      description: "The electric field created by a point charge at a distance r.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Electric Potential",
      formula: "V = k × q ÷ r",
      description: "Electric potential at a point due to a point charge.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Potential Difference",
      formula: "V = W ÷ q",
      description: "The work done (W) to move a charge (q) between two points in an electric field.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Relation Between E and V",
      formula: "E⃗ = -dV ÷ dr",
      description: "Electric field is the negative gradient of potential with respect to distance.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Capacitance",
      formula: "C = q ÷ V",
      description: "Capacitance is the ability of a system to store charge per unit potential difference.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Capacitance of Parallel Plate Capacitor",
      formula: "C = ε₀ × A ÷ d",
      description: "Capacitance is directly proportional to plate area and inversely proportional to separation.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Energy Stored in a Capacitor",
      formula: "U = ½ × C × V²",
      description: "The energy stored in a charged capacitor.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Combination of Capacitors (Parallel)",
      formula: "C_eq = C₁ + C₂ + C₃ + ...",
      description: "Capacitance adds directly in a parallel connection.",
    },
    {
      topic: "physics",
      chapter: "Static Electricity",
      name: "Combination of Capacitors (Series)",
      formula: "1 ÷ C_eq = 1 ÷ C₁ + 1 ÷ C₂ + 1 ÷ C₃ + ...",
      description: "Reciprocal addition for capacitors in series.",
    }
  ];
  