export const physics3 = [
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Electric Current",
      formula: "I = Q / t",
      description: "Current (I) is the rate of flow of charge (Q) per unit time (t).",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Ohm’s Law",
      formula: "V = IR",
      description: "Voltage (V) across a resistor is proportional to current (I) times resistance (R).",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Resistance",
      formula: "R = ρ * (L / A)",
      description: "Resistance depends on resistivity (ρ), length (L), and cross-sectional area (A) of the conductor.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Resistivity Temperature Relation",
      formula: "ρ = ρ₀[1 + α(T - T₀)]",
      description: "Resistivity changes with temperature; α is the temperature coefficient.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Power",
      formula: "P = VI = I²R = V² / R",
      description: "Power dissipated in a resistor is voltage times current or in terms of current and resistance.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Energy Dissipated",
      formula: "E = Pt = VI t",
      description: "Energy consumed over time (t) by electric current.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Kirchhoff’s Current Law (KCL)",
      formula: "Σ I_in = Σ I_out",
      description: "The total current entering a junction equals the total current leaving.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Kirchhoff’s Voltage Law (KVL)",
      formula: "Σ V = 0 (around a closed loop)",
      description: "Sum of all potential differences in a closed circuit loop equals zero.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Equivalent Resistance (Series)",
      formula: "R_eq = R₁ + R₂ + R₃ + ...",
      description: "Resistances add up directly in series.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Equivalent Resistance (Parallel)",
      formula: "1/R_eq = 1/R₁ + 1/R₂ + 1/R₃ + ...",
      description: "Reciprocal sum for resistors connected in parallel.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Drift Velocity",
      formula: "v_d = I / (n e A)",
      description: "Average velocity of electrons in a conductor where n is number density, e is charge of electron, A is cross-sectional area.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Electric Current in terms of Drift Velocity",
      formula: "I = n e A v_d",
      description: "Current is charge density times drift velocity and cross-sectional area.",
    },
    {
      topic: "physics",
      chapter: "Current Electricity",
      name: "Charge of an Electron",
      formula: "e = 1.6 × 10⁻¹⁹ C",
      description: "Fundamental charge of one electron.",
    },
  ];
  