export const physics9 = [
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Bohr’s Radius",
      formula: "r_n = n² * (h²) / (4 * π² * m * e² * Z)",
      description: "Radius of nth orbit of electron in a hydrogen-like atom (Z is atomic number, n is orbit number).",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Energy of Electron in nth Orbit (Bohr Model)",
      formula: "E_n = - (13.6 * Z²) / n²  (eV)",
      description: "Energy of electron in nth orbit for hydrogen-like atom.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Frequency of Photon Emitted",
      formula: "f = (E_i - E_f) / h",
      description: "Frequency of photon emitted when electron jumps from initial energy level E_i to final E_f.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Mass-Energy Equivalence",
      formula: "E = mc²",
      description: "Energy (E) equivalent to mass (m), c is speed of light.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Radioactive Decay Law",
      formula: "N = N₀ * e^(-λt)",
      description: "Number of undecayed nuclei (N) after time t; λ is decay constant.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Half-Life",
      formula: "T_½ = ln(2) / λ",
      description: "Time required for half of the radioactive nuclei to decay.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Activity",
      formula: "A = λN",
      description: "Number of decays per unit time.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Binding Energy",
      formula: "BE = Δm * c²",
      description: "Energy required to disassemble nucleus into its protons and neutrons; Δm is mass defect.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Mass Defect",
      formula: "Δm = Z * m_p + (A - Z) * m_n - m_nucleus",
      description: "Difference between total mass of individual nucleons and actual mass of nucleus.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Alpha Decay",
      formula: "A → A-4 + He⁴₂ (alpha particle)",
      description: "Emission of alpha particle decreases mass number by 4 and atomic number by 2.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Beta Decay",
      formula: "n → p + e⁻ + ν̅_e",
      description: "Neutron converts to proton, emitting an electron (beta particle) and antineutrino.",
    },
    {
      topic: "physics",
      chapter: "Atomic Model and Nuclear Physics",
      name: "Gamma Decay",
      formula: "Nucleus* → Nucleus + γ",
      description: "Emission of gamma ray photon from excited nucleus.",
    },
  ];
  