export const physics7 = [
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Density",
      formula: "ρ = m ÷ V",
      description: "Density (ρ) is mass (m) per unit volume (V) of a substance.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Relative Density",
      formula: "RD = ρ_substance ÷ ρ_water",
      description: "Relative density is the ratio of the density of a substance to the density of water.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Hooke's Law",
      formula: "F⃗ = k × x",
      description: "Force needed to stretch a spring is proportional to the extension (x), with k being the spring constant.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Stress",
      formula: "σ = F⃗ ÷ A",
      description: "Stress is the force (F) applied per unit area (A).",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Strain",
      formula: "ε = ΔL ÷ L",
      description: "Strain is the change in length (ΔL) divided by the original length (L); it has no unit.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Young's Modulus",
      formula: "Y = σ ÷ ε = (F⃗ × L) ÷ (A × ΔL)",
      description: "Young's modulus measures the stiffness of a material.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Elastic Potential Energy",
      formula: "E = ½ × k × x²",
      description: "Energy stored in a stretched or compressed spring.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Pressure",
      formula: "P = F⃗ ÷ A",
      description: "Pressure is the force applied per unit area.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Pressure in a Fluid",
      formula: "P = ρ × g × h",
      description: "Pressure at a depth h in a fluid of density ρ under gravity g.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Bulk Modulus",
      formula: "B = -ΔP ÷ (ΔV ÷ V)",
      description: "Bulk modulus measures a substance's resistance to uniform compression.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Volume Expansion",
      formula: "ΔV = V₀ × β × ΔT",
      description: "The change in volume ΔV due to temperature change ΔT; β is the coefficient of volume expansion.",
    },
    {
      topic: "physics",
      chapter: "Structure of Matter and Properties of Matter",
      name: "Linear Expansion",
      formula: "ΔL = L₀ × α × ΔT",
      description: "Change in length ΔL due to temperature change; α is the coefficient of linear expansion.",
    }
  ];
  