export const physics8 = [
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Time Period",
      formula: "T = 1 ÷ f",
      description: "Time period T is the time taken to complete one full cycle of motion. It is the reciprocal of frequency f.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Frequency",
      formula: "f = 1 ÷ T",
      description: "Frequency is the number of cycles per second in periodic motion.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Angular Frequency",
      formula: "ω = 2π × f = 2π ÷ T",
      description: "Angular frequency ω relates to frequency and time period.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Displacement in SHM",
      formula: "x(t) = A × sin(ωt + φ)",
      description: "Displacement x at time t for simple harmonic motion; A is amplitude, ω is angular frequency, and φ is phase constant.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Velocity in SHM",
      formula: "v(t) = A × ω × cos(ωt + φ)",
      description: "Velocity is the time derivative of displacement in SHM.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Acceleration in SHM",
      formula: "a(t) = -A × ω² × sin(ωt + φ) = -ω² × x",
      description: "Acceleration is proportional to and opposite in direction to displacement in SHM.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Maximum Velocity",
      formula: "vₘₐₓ = A × ω",
      description: "Maximum speed in SHM occurs at mean position.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Maximum Acceleration",
      formula: "aₘₐₓ = A × ω²",
      description: "Maximum acceleration in SHM occurs at extreme positions.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Total Energy in SHM",
      formula: "E = ½ × k × A² = ½ × m × ω² × A²",
      description: "Total mechanical energy of a body in SHM is constant and depends on amplitude and mass.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Kinetic Energy in SHM",
      formula: "KE = ½ × m × ω² × (A² - x²)",
      description: "Kinetic energy at position x in SHM.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Potential Energy in SHM",
      formula: "PE = ½ × m × ω² × x²",
      description: "Potential energy at displacement x in SHM.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Spring Force (Hooke's Law)",
      formula: "F⃗ = -k × x",
      description: "The restoring force in a spring is proportional to displacement and acts in the opposite direction.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Time Period of Mass-Spring System",
      formula: "T = 2π × √(m ÷ k)",
      description: "Time period of SHM for a mass m attached to a spring with constant k.",
    },
    {
      topic: "physics",
      chapter: "Periodic Motion",
      name: "Time Period of Simple Pendulum",
      formula: "T = 2π × √(L ÷ g)",
      description: "Time period of a simple pendulum depends on its length L and acceleration due to gravity g.",
    }
  ];
  