export const physics9 = [
    {
      topic: "physics",
      chapter: "Wave",
      name: "Wave Speed",
      formula: "v = f × λ",
      description: "The speed v of a wave is the product of its frequency f and wavelength λ.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Time Period",
      formula: "T = 1 ÷ f",
      description: "The time period T is the reciprocal of the frequency f.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Frequency",
      formula: "f = 1 ÷ T",
      description: "Frequency is the number of wave cycles per second, and is the inverse of the time period.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Angular Frequency",
      formula: "ω = 2π × f",
      description: "Angular frequency ω is related to linear frequency f by 2π.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Wave Number",
      formula: "k = 2π ÷ λ",
      description: "Wave number k is the spatial frequency of a wave, representing the number of wavelengths per unit distance.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "General Wave Equation",
      formula: "y(x, t) = A × sin(kx - ωt + φ)",
      description: "Describes a sinusoidal wave moving in the +x direction; A is amplitude, k is wave number, ω is angular frequency, and φ is phase constant.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Path Difference and Phase Difference",
      formula: "Δφ = (2π ÷ λ) × Δx",
      description: "Phase difference Δφ is proportional to the path difference Δx.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Principle of Superposition",
      formula: "y = y₁ + y₂",
      description: "When two or more waves overlap, the resultant displacement is the sum of individual displacements.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Standing Wave Wavelength (String or Pipe Closed at One End)",
      formula: "λ = 4L ÷ n (n = 1, 3, 5...)",
      description: "In a pipe closed at one end, only odd harmonics are present; L is length of pipe.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Standing Wave Wavelength (Pipe Open at Both Ends or String)",
      formula: "λ = 2L ÷ n (n = 1, 2, 3...)",
      description: "In a pipe open at both ends (or vibrating string), all harmonics are present.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Speed of Sound in Medium",
      formula: "v = √(γ × P ÷ ρ)",
      description: "Speed of sound in a gas depends on the adiabatic constant γ, pressure P, and density ρ of the medium.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Doppler Effect (Source Moving Towards Observer)",
      formula: "f' = f × (v ÷ (v - vₛ))",
      description: "Apparent frequency increases when the source approaches the observer.",
    },
    {
      topic: "physics",
      chapter: "Wave",
      name: "Doppler Effect (Observer Moving Towards Source)",
      formula: "f' = f × ((v + vₒ) ÷ v)",
      description: "Apparent frequency increases when the observer approaches the source.",
    }
  ];
  